language: node_js
node_js:
- node
addons:
  ssh_known_hosts: ${sftp_server}
before_install:
- openssl aes-256-cbc -K $encrypted_703dd908551c_key -iv $encrypted_703dd908551c_iv
  -in deploy_key.enc -out ./deploy_key -d
- npm install --global npm@lts
cache:
  directories:
  - node_modules
script:
- npm run lint
- npm run build
deploy:
- provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist ${sftp_user}@${sftp_server}:${sftp_path}
  on:
    branch: master
