language: node_js

node_js:
  - node

before_install:
  - npm install --global npm@lts
  - eval "$(ssh-agent -s)"
  - openssl aes-256-cbc -K $encrypted_dc4c0df7bb33_key -iv $encrypted_dc4c0df7bb33_iv -in id_ed25519.enc -out id_ed25519 -d
  - chmod 600 id_ed25519
  - ssh-add id_ed25519

cache:
  directories:
    - node_modules

script:
  - npm run lint
  # set publicPath to make gh-pages work
  - npm run client:build -- --output-public-path . --define "__reactRouter__='HashRouter'"

deploy:
  - provider: script
    skip_cleanup: true
    script: npm run deploy -- -b gh-pages -r git@github.com:${TRAVIS_REPO_SLUG}.git
    on:
      branch: master
