language: node_js

node_js:
  - node

before_install:
  - npm install --global npm@lts

cache:
  directories:
    - node_modules

script:
  - npm run lint
  # set publicPath to make gh-pages work
  - npm run build -- --output-public-path .

deploy:
  - provider: script
    skip_cleanup: true
    script: ./.travis-deploy.sh
    on:
      branch: master
