language: node_js

node_js:
  - node

before_install:
  - npm install --global npm@lts

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run build

deploy:
  - provider: script
    skip_cleanup: true
    script: node .travis-deploy.js
    on:
      branch: master
